### ISSUE TITLE
error[E0463]: can't find crate for `std` when compiling from source

### ISSUE THREAD

**Issue by YiweiNiu** [10XGenomics/scHLAcount#5]
Hi,

I am trying to compiling `scHLAcount` from source code, since the the binary version requires high version of GLIBC.

Here is the code and the error information

```shell
$  git clone git@github.com:10XGenomics/scHLAcount.git scHLAcount.0.1.0
$ cd scHLAcount.0.1.0
$ cargo build --release
...
   Compiling proc-macro2 v0.4.30
   Compiling semver-parser v0.7.0
   Compiling proc-macro2 v1.0.1
   Compiling unicode-xid v0.1.0
   Compiling unicode-xid v0.2.0
   Compiling syn v0.15.44
   Compiling libc v0.2.62
   Compiling cc v1.0.41
   Compiling syn v1.0.5
   Compiling arrayvec v0.4.11
   Compiling memchr v2.2.1
   Compiling autocfg v0.1.6
error[E0463]: can't find crate for `std`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: Could not compile `proc-macro2`.
warning: build failed, waiting for other jobs to finish...
error[E0463]: can't find crate for `std`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: Could not compile `autocfg`.
warning: build failed, waiting for other jobs to finish...
error[E0463]: can't find crate for `std`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: Could not compile `syn`.
warning: build failed, waiting for other jobs to finish...
error[E0463]: can't find crate for `std`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: Could not compile `proc-macro2`.
warning: build failed, waiting for other jobs to finish...
error[E0463]: can't find crate for `core`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: Could not compile `unicode-xid`.
warning: build failed, waiting for other jobs to finish...
error[E0463]: can't find crate for `core`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: Could not compile `unicode-xid`.
warning: build failed, waiting for other jobs to finish...
error[E0463]: can't find crate for `std`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: Could not compile `libc`.
warning: build failed, waiting for other jobs to finish...
error[E0463]: can't find crate for `std`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: Could not compile `syn`.
warning: build failed, waiting for other jobs to finish...
error[E0463]: can't find crate for `std`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: Could not compile `cc`.
warning: build failed, waiting for other jobs to finish...
error[E0463]: can't find crate for `std`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: Could not compile `semver-parser`.
warning: build failed, waiting for other jobs to finish...
error[E0463]: can't find crate for `std`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: Could not compile `arrayvec`.
warning: build failed, waiting for other jobs to finish...
error[E0463]: can't find crate for `std`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: Could not compile `memchr`.

To learn more, run the command again with --verbose.

$ rustc --explain E0463
A plugin/crate was declared but cannot be found. Erroneous code example:

#![feature(plugin)]
#![plugin(cookie_monster)] // error: can't find crate for `cookie_monster`
extern crate cake_is_a_lie; // error: can't find crate for `cake_is_a_lie`

You need to link your code to the relevant crate in order to be able to use it
(through Cargo or the `-L` option of rustc example). Plugins are crates as
well, and you link to them the same way.
```

I tried Google but could not find anything helpful, and I know nothing about Rust.

Do you know how to solve this? Any comments or help would be appreciated.

Bests,
Yiwei Niu

**Comment by YiweiNiu** [comment]
Thank you for your reply!

I re-installed Rust and compiled again. But I encountered the following error.

```shell
niuyw@admin:~/software/scHLAcount.0.1.0$ RUST_BACKTRACE=1 cargo build --release
   Compiling rust-htslib v0.24.1-alpha.0 (https://github.com/rust-bio/rust-htslib.git?rev=18072e0faf909ed19da4d1226a35c239a4b4292e#18072e0f)
error: failed to run custom build command for `rust-htslib v0.24.1-alpha.0 (https://github.com/rust-bio/rust-htslib.git?rev=18072e0faf909ed19da4d1226a35c239a4b4292e#18072e0f)`

Caused by:
  process didn't exit successfully: `/home/niuyw/software/scHLAcount.0.1.0/target/release/build/rust-htslib-0ea205827c1d0764/build-script-build` (exit code: 101)
--- stdout
OPT_LEVEL = Some("3")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = None
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
DEBUG = Some("true")
echo '/* Default config.h generated by Makefile */' > config.h
echo '#define HAVE_LIBBZ2 1' >> config.h
echo '#define HAVE_LIBLZMA 1' >> config.h
echo '#define HAVE_LZMA_H 1' >> config.h
echo '#define HAVE_FSEEKO 1' >> config.h
echo '#define HAVE_DRAND48 1' >> config.h
cc -O3 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer -m64 -static -I /home/niuyw/software/scHLAcount.0.1.0/target/release/build/bzip2-sys-65b10b80b0074e34/out/include -I.  -c -o kfunc.o kfunc.c
cc -O3 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer -m64 -static -I /home/niuyw/software/scHLAcount.0.1.0/target/release/build/bzip2-sys-65b10b80b0074e34/out/include -I.  -c -o knetfile.o knetfile.c
cc -O3 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer -m64 -static -I /home/niuyw/software/scHLAcount.0.1.0/target/release/build/bzip2-sys-65b10b80b0074e34/out/include -I.  -c -o kstring.o kstring.c
cc -O3 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer -m64 -static -I /home/niuyw/software/scHLAcount.0.1.0/target/release/build/bzip2-sys-65b10b80b0074e34/out/include -I.  -c -o bcf_sr_sort.o bcf_sr_sort.c
cc -O3 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer -m64 -static -I /home/niuyw/software/scHLAcount.0.1.0/target/release/build/bzip2-sys-65b10b80b0074e34/out/include -I.  -c -o bgzf.o bgzf.c
cc -O3 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer -m64 -static -I /home/niuyw/software/scHLAcount.0.1.0/target/release/build/bzip2-sys-65b10b80b0074e34/out/include -I.  -c -o errmod.o errmod.c
cc -O3 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer -m64 -static -I /home/niuyw/software/scHLAcount.0.1.0/target/release/build/bzip2-sys-65b10b80b0074e34/out/include -I.  -c -o faidx.o faidx.c
cc -O3 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer -m64 -static -I /home/niuyw/software/scHLAcount.0.1.0/target/release/build/bzip2-sys-65b10b80b0074e34/out/include -I.  -c -o hfile.o hfile.c
cc -O3 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer -m64 -static -I /home/niuyw/software/scHLAcount.0.1.0/target/release/build/bzip2-sys-65b10b80b0074e34/out/include -I.  -c -o hfile_net.o hfile_net.c
echo '#define HTS_VERSION "1.9-1-gd2c86b3"' > version.h
cc -O3 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer -m64 -static -I /home/niuyw/software/scHLAcount.0.1.0/target/release/build/bzip2-sys-65b10b80b0074e34/out/include -I.  -c -o hts.o hts.c
cc -O3 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer -m64 -static -I /home/niuyw/software/scHLAcount.0.1.0/target/release/build/bzip2-sys-65b10b80b0074e34/out/include -I.  -c -o hts_os.o hts_os.c
cc -O3 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer -m64 -static -I /home/niuyw/software/scHLAcount.0.1.0/target/release/build/bzip2-sys-65b10b80b0074e34/out/include -I.  -c -o md5.o md5.c
cc -O3 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer -m64 -static -I /home/niuyw/software/scHLAcount.0.1.0/target/release/build/bzip2-sys-65b10b80b0074e34/out/include -I.  -c -o multipart.o multipart.c
cc -O3 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer -m64 -static -I /home/niuyw/software/scHLAcount.0.1.0/target/release/build/bzip2-sys-65b10b80b0074e34/out/include -I.  -c -o probaln.o probaln.c
cc -O3 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer -m64 -static -I /home/niuyw/software/scHLAcount.0.1.0/target/release/build/bzip2-sys-65b10b80b0074e34/out/include -I.  -c -o realn.o realn.c
cc -O3 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer -m64 -static -I /home/niuyw/software/scHLAcount.0.1.0/target/release/build/bzip2-sys-65b10b80b0074e34/out/include -I.  -c -o regidx.o regidx.c
cc -O3 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer -m64 -static -I /home/niuyw/software/scHLAcount.0.1.0/target/release/build/bzip2-sys-65b10b80b0074e34/out/include -I.  -c -o sam.o sam.c
cc -O3 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer -m64 -static -I /home/niuyw/software/scHLAcount.0.1.0/target/release/build/bzip2-sys-65b10b80b0074e34/out/include -I.  -c -o synced_bcf_reader.o synced_bcf_reader.c
cc -O3 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer -m64 -static -I /home/niuyw/software/scHLAcount.0.1.0/target/release/build/bzip2-sys-65b10b80b0074e34/out/include -I.  -c -o vcf_sweep.o vcf_sweep.c
cc -O3 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer -m64 -static -I /home/niuyw/software/scHLAcount.0.1.0/target/release/build/bzip2-sys-65b10b80b0074e34/out/include -I.  -c -o tbx.o tbx.c
cc -O3 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer -m64 -static -I /home/niuyw/software/scHLAcount.0.1.0/target/release/build/bzip2-sys-65b10b80b0074e34/out/include -I.  -c -o textutils.o textutils.c
cc -O3 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer -m64 -static -I /home/niuyw/software/scHLAcount.0.1.0/target/release/build/bzip2-sys-65b10b80b0074e34/out/include -I.  -c -o thread_pool.o thread_pool.c
cc -O3 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer -m64 -static -I /home/niuyw/software/scHLAcount.0.1.0/target/release/build/bzip2-sys-65b10b80b0074e34/out/include -I.  -c -o vcf.o vcf.c
cc -O3 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer -m64 -static -I /home/niuyw/software/scHLAcount.0.1.0/target/release/build/bzip2-sys-65b10b80b0074e34/out/include -I.  -c -o vcfutils.o vcfutils.c
cc -O3 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer -m64 -static -I /home/niuyw/software/scHLAcount.0.1.0/target/release/build/bzip2-sys-65b10b80b0074e34/out/include -I.  -c -o cram/cram_codecs.o cram/cram_codecs.c
cc -O3 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer -m64 -static -I /home/niuyw/software/scHLAcount.0.1.0/target/release/build/bzip2-sys-65b10b80b0074e34/out/include -I.  -c -o cram/cram_decode.o cram/cram_decode.c
cc -O3 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer -m64 -static -I /home/niuyw/software/scHLAcount.0.1.0/target/release/build/bzip2-sys-65b10b80b0074e34/out/include -I.  -c -o cram/cram_encode.o cram/cram_encode.c
cc -O3 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer -m64 -static -I /home/niuyw/software/scHLAcount.0.1.0/target/release/build/bzip2-sys-65b10b80b0074e34/out/include -I.  -c -o cram/cram_external.o cram/cram_external.c
cc -O3 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer -m64 -static -I /home/niuyw/software/scHLAcount.0.1.0/target/release/build/bzip2-sys-65b10b80b0074e34/out/include -I.  -c -o cram/cram_index.o cram/cram_index.c
cc -O3 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer -m64 -static -I /home/niuyw/software/scHLAcount.0.1.0/target/release/build/bzip2-sys-65b10b80b0074e34/out/include -I.  -c -o cram/cram_io.o cram/cram_io.c
cc -O3 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer -m64 -static -I /home/niuyw/software/scHLAcount.0.1.0/target/release/build/bzip2-sys-65b10b80b0074e34/out/include -I.  -c -o cram/cram_samtools.o cram/cram_samtools.c
cc -O3 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer -m64 -static -I /home/niuyw/software/scHLAcount.0.1.0/target/release/build/bzip2-sys-65b10b80b0074e34/out/include -I.  -c -o cram/cram_stats.o cram/cram_stats.c
cc -O3 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer -m64 -static -I /home/niuyw/software/scHLAcount.0.1.0/target/release/build/bzip2-sys-65b10b80b0074e34/out/include -I.  -c -o cram/files.o cram/files.c
cc -O3 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer -m64 -static -I /home/niuyw/software/scHLAcount.0.1.0/target/release/build/bzip2-sys-65b10b80b0074e34/out/include -I.  -c -o cram/mFILE.o cram/mFILE.c
cc -O3 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer -m64 -static -I /home/niuyw/software/scHLAcount.0.1.0/target/release/build/bzip2-sys-65b10b80b0074e34/out/include -I.  -c -o cram/open_trace_file.o cram/open_trace_file.c
cc -O3 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer -m64 -static -I /home/niuyw/software/scHLAcount.0.1.0/target/release/build/bzip2-sys-65b10b80b0074e34/out/include -I.  -c -o cram/pooled_alloc.o cram/pooled_alloc.c
cc -O3 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer -m64 -static -I /home/niuyw/software/scHLAcount.0.1.0/target/release/build/bzip2-sys-65b10b80b0074e34/out/include -I.  -c -o cram/rANS_static.o cram/rANS_static.c
cc -O3 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer -m64 -static -I /home/niuyw/software/scHLAcount.0.1.0/target/release/build/bzip2-sys-65b10b80b0074e34/out/include -I.  -c -o cram/sam_header.o cram/sam_header.c
cc -O3 -ffunction-sections -fdata-sections -fPIC -g -fno-omit-frame-pointer -m64 -static -I /home/niuyw/software/scHLAcount.0.1.0/target/release/build/bzip2-sys-65b10b80b0074e34/out/include -I.  -c -o cram/string_alloc.o cram/string_alloc.c
ar -rc libhts.a kfunc.o knetfile.o kstring.o bcf_sr_sort.o bgzf.o errmod.o faidx.o hfile.o hfile_net.o hts.o hts_os.o md5.o multipart.o probaln.o realn.o regidx.o sam.o synced_bcf_reader.o vcf_sweep.o tbx.o textutils.o thread_pool.o vcf.o vcfutils.o cram/cram_codecs.o cram/cram_decode.o cram/cram_encode.o cram/cram_external.o cram/cram_index.o cram/cram_io.o cram/cram_samtools.o cram/cram_stats.o cram/files.o cram/mFILE.o cram/open_trace_file.o cram/pooled_alloc.o cram/rANS_static.o cram/sam_header.o cram/string_alloc.o
ranlib libhts.a
running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-static" "-I" "/home/niuyw/software/scHLAcount.0.1.0/target/release/build/bzip2-sys-65b10b80b0074e34/out/include" "-o" "/home/niuyw/software/scHLAcount.0.1.0/target/release/build/rust-htslib-146bb840a8acec7b/out/wrapper.o" "-c" "wrapper.c"
exit code: 0
AR_x86_64-unknown-linux-gnu = None
AR_x86_64_unknown_linux_gnu = None
HOST_AR = None
AR = None
running: "ar" "crs" "/home/niuyw/software/scHLAcount.0.1.0/target/release/build/rust-htslib-146bb840a8acec7b/out/libwrapper.a" "/home/niuyw/software/scHLAcount.0.1.0/target/release/build/rust-htslib-146bb840a8acec7b/out/wrapper.o"
exit code: 0
cargo:rustc-link-lib=static=wrapper
cargo:rustc-link-search=native=/home/niuyw/software/scHLAcount.0.1.0/target/release/build/rust-htslib-146bb840a8acec7b/out
cargo:warning=couldn't execute `llvm-config --prefix` (error: No such file or directory (os error 2))
cargo:warning=set the LLVM_CONFIG_PATH environment variable to a valid `llvm-config` executable

--- stderr
thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any valid shared libraries matching: [\'libclang.so\', \'libclang-*.so\', \'libclang.so.*\'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', src/libcore/result.rs:999:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: rust_begin_unwind
             at src/libstd/panicking.rs:311
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::result::unwrap_failed
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/macros.rs:18
  11: core::result::Result<T,E>::expect
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/result.rs:827
  12: <bindgen::ensure_libclang_is_loaded::LIBCLANG as core::ops::deref::Deref>::deref::__static_ref_initialize
             at /home/niuyw/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/bindgen-0.51.0/src/lib.rs:1711
  13: core::ops::function::FnOnce::call_once
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/ops/function.rs:231
  14: lazy_static::lazy::Lazy<T>::get::{{closure}}
             at /home/niuyw/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/lazy_static-1.4.0/src/inline_lazy.rs:31
  15: std::sync::once::Once::call_once::{{closure}}
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/sync/once.rs:225
  16: std::sync::once::Once::call_inner
             at src/libstd/sync/once.rs:392
  17: std::sync::once::Once::call_once
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/sync/once.rs:225
  18: lazy_static::lazy::Lazy<T>::get
             at /home/niuyw/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/lazy_static-1.4.0/src/inline_lazy.rs:30
  19: <bindgen::ensure_libclang_is_loaded::LIBCLANG as core::ops::deref::Deref>::deref::__stability
             at /home/niuyw/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/bindgen-0.51.0/<::lazy_static::__lazy_static_internal macros>:12
  20: <bindgen::ensure_libclang_is_loaded::LIBCLANG as core::ops::deref::Deref>::deref
             at /home/niuyw/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/bindgen-0.51.0/<::lazy_static::__lazy_static_internal macros>:13
  21: bindgen::ensure_libclang_is_loaded
             at /home/niuyw/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/bindgen-0.51.0/src/lib.rs:1718
  22: bindgen::Bindings::generate
             at /home/niuyw/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/bindgen-0.51.0/src/lib.rs:1733
  23: bindgen::Builder::generate
             at /home/niuyw/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/bindgen-0.51.0/src/lib.rs:1228
  24: build_script_build::main
             at ./build.rs:84
  25: std::rt::lang_start::{{closure}}
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/rt.rs:64
  26: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  27: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  28: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  29: std::panicking::try
             at src/libstd/panicking.rs:275
  30: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  31: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  32: main
  33: __libc_start_main
  34: <unknown>
```
 
Sorry if the question is too obvious.

Bests,
Yiwei Niu

**Comment by pmarks** [comment]
@YiweiNiu I've added a new binary build that will work on older linuxes: https://github.com/10XGenomics/scHLAcount/releases/download/0.1.0/sc_hla_count_linux

To build from source, you need to install the following packages: `llvm-dev` `libclang-dev` and `clang` ([see here](https://rust-lang.github.io/rust-bindgen/requirements.html) for details)

**Comment by YiweiNiu** [comment]
Thank you very much! The binary works now.
